-- Fresco Grow Lab schema (generated from supabase/migrations; do not edit).
-- Paste into your Supabase project's SQL editor and run it once.
-- Personal projects used with only a publishable key may also want
-- supabase/snippets/visitor-project-writes.sql from the repository.

-- ===== 20260929000100_temperature_readings.sql =====

-- Grow-bag temperature telemetry. One row per firmware upload; the full
-- firmware packet (all probe channels) is stored as jsonb in `payload`.
-- See docs/data.md for the packet shape.

create table if not exists public.temperature_readings (
  -- "by default" (not "always") so rows copied from another project keep
  -- their original ids (npm run supabase:copy).
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null default 'fresco-main',
  payload jsonb not null,

  constraint temperature_readings_payload_is_packet
    check (jsonb_typeof(payload) = 'object' and jsonb_typeof(payload -> 'channels') = 'array'),
  constraint temperature_readings_device_id_length
    check (char_length(device_id) between 1 and 32)
);

-- Upgrades tables created from the original schema (no device_id).
alter table public.temperature_readings
  add column if not exists device_id text not null default 'fresco-main';

create index if not exists temperature_readings_created_at_idx
  on public.temperature_readings (created_at desc);

create index if not exists temperature_readings_device_created_at_idx
  on public.temperature_readings (device_id, created_at desc);

comment on table public.temperature_readings is
  'ESP32 DS18B20 uploads: one jsonb firmware packet per row.';
comment on column public.temperature_readings.device_id is
  'Kit boards send their provisioned device id; the original board uses the default.';

-- ===== 20260929000200_irrigation_events.sql =====

-- Watering events with their 10-minute checkpoint weights. One row per
-- watering; `weight_logs` holds [{ slotAt, weighedAt, massKg, note }].
--
-- History: the first schema stored pre_mass_kg / post_mass_kg /
-- drained_mass_kg / drained_at. Those were replaced by cutoff_at + weight_logs;
-- the statements after the table upgrade such projects in place.

create table if not exists public.irrigation_events (
  id bigint generated by default as identity primary key,
  bag_id text not null default 'bag-1',
  watered_at timestamptz not null default now(),
  -- 6 PM Manila time on the watering date; the weigh window closes then.
  cutoff_at timestamptz not null,
  water_l numeric(5,2) not null default 2.0,
  water_temp_c numeric(4,1),
  weight_logs jsonb not null default '[]'::jsonb,
  note text,
  created_at timestamptz not null default now(),
  archived_at timestamptz,

  constraint irrigation_events_weight_logs_is_array
    check (jsonb_typeof(weight_logs) = 'array'),
  constraint irrigation_events_water_l_positive
    check (water_l > 0),
  constraint irrigation_events_water_temp_range
    check (water_temp_c is null or water_temp_c between 0 and 60),
  constraint irrigation_events_cutoff_after_watering
    check (cutoff_at > watered_at)
);

-- In-place upgrade for the first schema (no-ops on new projects). Legacy
-- mass columns are left for you to export and drop.
alter table public.irrigation_events
  add column if not exists cutoff_at timestamptz,
  add column if not exists weight_logs jsonb not null default '[]'::jsonb;

update public.irrigation_events
set cutoff_at = (((watered_at at time zone 'Asia/Manila')::date + time '18:00')
  at time zone 'Asia/Manila')
where cutoff_at is null;

alter table public.irrigation_events alter column cutoff_at set not null;

create index if not exists irrigation_events_bag_watered_at_idx
  on public.irrigation_events (bag_id, watered_at desc);

create index if not exists irrigation_events_open_window_idx
  on public.irrigation_events (bag_id, cutoff_at)
  where archived_at is null;

comment on table public.irrigation_events is
  'Grow-bag waterings and their checkpoint weigh logs.';

-- ===== 20260929000300_rain_gauge.sql =====

-- Optional rain gauge sync. The dashboard stores rain sessions locally
-- (IndexedDB) and upserts them here on demand via POST /api/rain-gauge/sync.
-- Column names match web/src/lib/rain-gauge/sync.ts.

create table if not exists public.rain_gauge_sessions (
  id text primary key,
  label text not null,
  -- ap: ESP32 access point, usb: kit firmware over Web Serial, sample: demo
  source text not null default 'ap' check (source in ('ap', 'usb', 'sample')),
  started_at timestamptz not null,
  ended_at timestamptz,
  ap_base_url text,
  ml_per_tip numeric check (ml_per_tip is null or ml_per_tip > 0),
  catchment_area_cm2 numeric check (catchment_area_cm2 is null or catchment_area_cm2 > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.rain_gauge_readings (
  id text primary key,
  session_id text not null references public.rain_gauge_sessions (id) on delete cascade,
  received_at timestamptz not null,
  source text not null default 'ap' check (source in ('ap', 'usb', 'sample', 'import')),
  seq bigint,
  device_ms bigint,
  edges bigint not null check (edges >= 0),
  tips numeric not null check (tips >= 0),
  -- Firmware counts magnet-in and magnet-out edges; odd = mid-tip.
  pending_half_tip boolean generated always as (edges % 2 = 1) stored,
  last_edge_ms bigint,
  rainfall_ml numeric not null,
  rainfall_mm numeric,
  rate_ml_per_min numeric not null,
  rate_mm_per_hr numeric,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

-- Upgrades tables created from the original schema, which lacked the
-- columns the sync route writes.
alter table public.rain_gauge_readings
  add column if not exists source text not null default 'ap',
  add column if not exists payload jsonb not null default '{}'::jsonb;

create index if not exists rain_gauge_readings_session_received_idx
  on public.rain_gauge_readings (session_id, received_at);

-- ===== 20260929000400_row_level_security.sql =====

-- Row Level Security.
--
-- Who writes what:
--   * ESP32 boards use the PUBLISHABLE (anon) key and may only INSERT
--     temperature rows (the key is readable off the chip, so it gets nothing else).
--   * The Next.js API routes use the SECRET (service_role) key, which bypasses
--     RLS, for irrigation writes and rain sync.
--   * Browsers never write directly; anon may read dashboard tables.
--
-- A visitor pointing the dashboard at their own project with only a
-- publishable key also needs supabase/snippets/visitor-project-writes.sql.

alter table public.temperature_readings enable row level security;
alter table public.irrigation_events enable row level security;
alter table public.rain_gauge_sessions enable row level security;
alter table public.rain_gauge_readings enable row level security;

-- Recreate policies idempotently (older projects used different names).
drop policy if exists "device can insert readings" on public.temperature_readings;
drop policy if exists "dashboard can read readings" on public.temperature_readings;
drop policy if exists "anon read irrigation" on public.irrigation_events;
drop policy if exists "anon write irrigation" on public.irrigation_events;
drop policy if exists "anon edit irrigation" on public.irrigation_events;
drop policy if exists "anon read rain sessions" on public.rain_gauge_sessions;
drop policy if exists "anon read rain readings" on public.rain_gauge_readings;

create policy "device can insert readings"
  on public.temperature_readings
  for insert
  to anon, authenticated
  with check (true);

create policy "dashboard can read readings"
  on public.temperature_readings
  for select
  to anon, authenticated
  using (true);

create policy "dashboard can read irrigation"
  on public.irrigation_events
  for select
  to anon, authenticated
  using (true);

create policy "dashboard can read rain sessions"
  on public.rain_gauge_sessions
  for select
  to anon, authenticated
  using (true);

create policy "dashboard can read rain readings"
  on public.rain_gauge_readings
  for select
  to anon, authenticated
  using (true);

-- ===== 20260929000500_views.sql =====

-- Relational views over the jsonb firmware packets, for the SQL editor,
-- BI tools and CSV exports. security_invoker makes them respect the caller's
-- RLS instead of the view owner's.

create or replace view public.temperature_channels
  with (security_invoker = true) as
select
  r.id as reading_id,
  r.created_at,
  r.device_id,
  (r.payload ->> 'seq')::bigint as seq,
  channel ->> 'id' as channel_id,
  (channel ->> 'pin')::int as pin,
  channel ->> 'ts' as status,
  (channel ->> 'tc')::numeric as celsius
from public.temperature_readings r
cross join lateral jsonb_array_elements(r.payload -> 'channels') as channel;

comment on view public.temperature_channels is
  'One row per probe per upload, flattened from temperature_readings.payload.';

create or replace view public.temperature_hourly
  with (security_invoker = true) as
select
  device_id,
  date_trunc('hour', created_at) as hour,
  channel_id,
  round(avg(celsius), 2) as mean_c,
  round(min(celsius), 2) as min_c,
  round(max(celsius), 2) as max_c,
  count(*) filter (where status = 'ok') as ok_count,
  count(*) as sample_count
from public.temperature_channels
group by device_id, date_trunc('hour', created_at), channel_id;

comment on view public.temperature_hourly is
  'Hourly per-probe statistics (UTC hours).';

create or replace view public.irrigation_checkpoints
  with (security_invoker = true) as
select
  e.id as event_id,
  e.bag_id,
  e.watered_at,
  e.cutoff_at,
  (log ->> 'slotAt')::timestamptz as slot_at,
  (log ->> 'weighedAt')::timestamptz as weighed_at,
  (log ->> 'massKg')::numeric as mass_kg,
  log ->> 'note' as note
from public.irrigation_events e
cross join lateral jsonb_array_elements(e.weight_logs) as log
where e.archived_at is null;

comment on view public.irrigation_checkpoints is
  'One row per logged checkpoint weight of active waterings.';
