-- Watering events with their 10-minute checkpoint weights. One row per
-- watering; `weight_logs` holds [{ slotAt, weighedAt, massKg, note }].
--
-- History: the first schema stored pre_mass_kg / post_mass_kg /
-- drained_mass_kg / drained_at. Those were replaced by cutoff_at + weight_logs;
-- the statements after the table upgrade such projects in place.

create table if not exists public.irrigation_events (
  id bigint generated by default as identity primary key,
  bag_id text not null default 'bag-1',
  watered_at timestamptz not null default now(),
  -- 6 PM Manila time on the watering date; the weigh window closes then.
  cutoff_at timestamptz not null,
  water_l numeric(5,2) not null default 2.0,
  water_temp_c numeric(4,1),
  weight_logs jsonb not null default '[]'::jsonb,
  note text,
  created_at timestamptz not null default now(),
  archived_at timestamptz,

  constraint irrigation_events_weight_logs_is_array
    check (jsonb_typeof(weight_logs) = 'array'),
  constraint irrigation_events_water_l_positive
    check (water_l > 0),
  constraint irrigation_events_water_temp_range
    check (water_temp_c is null or water_temp_c between 0 and 60),
  constraint irrigation_events_cutoff_after_watering
    check (cutoff_at > watered_at)
);

-- In-place upgrade for the first schema (no-ops on new projects). Legacy
-- mass columns are left for you to export and drop.
alter table public.irrigation_events
  add column if not exists cutoff_at timestamptz,
  add column if not exists weight_logs jsonb not null default '[]'::jsonb;

update public.irrigation_events
set cutoff_at = (((watered_at at time zone 'Asia/Manila')::date + time '18:00')
  at time zone 'Asia/Manila')
where cutoff_at is null;

alter table public.irrigation_events alter column cutoff_at set not null;

create index if not exists irrigation_events_bag_watered_at_idx
  on public.irrigation_events (bag_id, watered_at desc);

create index if not exists irrigation_events_open_window_idx
  on public.irrigation_events (bag_id, cutoff_at)
  where archived_at is null;

comment on table public.irrigation_events is
  'Grow-bag waterings and their checkpoint weigh logs.';
