-- Grow-bag temperature telemetry. One row per firmware upload; the full
-- firmware packet (all probe channels) is stored as jsonb in `payload`.
-- See docs/data.md for the packet shape.

create table if not exists public.temperature_readings (
  -- "by default" (not "always") so rows copied from another project keep
  -- their original ids (npm run supabase:copy).
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  device_id text not null default 'fresco-main',
  payload jsonb not null,

  constraint temperature_readings_payload_is_packet
    check (jsonb_typeof(payload) = 'object' and jsonb_typeof(payload -> 'channels') = 'array'),
  constraint temperature_readings_device_id_length
    check (char_length(device_id) between 1 and 32)
);

-- Upgrades tables created from the original schema (no device_id).
alter table public.temperature_readings
  add column if not exists device_id text not null default 'fresco-main';

create index if not exists temperature_readings_created_at_idx
  on public.temperature_readings (created_at desc);

create index if not exists temperature_readings_device_created_at_idx
  on public.temperature_readings (device_id, created_at desc);

comment on table public.temperature_readings is
  'ESP32 DS18B20 uploads: one jsonb firmware packet per row.';
comment on column public.temperature_readings.device_id is
  'Kit boards send their provisioned device id; the original board uses the default.';
